### PR TITLE
Merge modeac handling fix into master to resolve issue #18

### PR DESCRIPTION
**Pull request by Romeo-Golf**
Merge modeac handling fix into master to resolve issue #18

### CODE REVIEW

**Comment by mutability** [comment]
It's already on dev, it'll hit master when I do a release.

**Comment by Romeo-Golf** [comment]
Thanks, is there an ETA on this bug fix being pushed to the master branch to resolve the user reported issues? :)

**Comment by mutability** [comment]
Nope.

**Comment by Romeo-Golf** [comment]
Useful... are you waiting further testing or is there anything we can assist with to prevent an increasing number of users from downloading the master release on the incorrect assumption that it is not broken? ;)

**Comment by mutability** [comment]
Just check out the 0.2.7 tag or check out the dev branch.

I assume that if you have some requirement for release stability then you do your own testing and release engineering. I'm not going to do it for you.

**Comment by Romeo-Golf** [comment]
I think the wider user base has a not unreasonable expectation that this code does what it says on the tin, ie reports MLAT data to your MLAT server code... which 2.8.0 has been shown not to do :)

I think this particular issue may have come up before so I will do my part by ensuring any code which expects a working mlat client has a means to upgrade, or downgrade, to a known good version.

However given that the current 0.2.8 release is broken, and the change in the dev branch has been confirmed to fix the issue, is there any reason not to push this out to the master branch so that the majority of the users can benefit from this?

**Comment by mutability** [comment]
I release this code because I think it's useful to others _as a starting point_. The fact that no one else has actually picked up the support load and just wants to use it out of the box is not my problem and it does not obligate me to urgently push releases if something breaks. A release will happen when it needs to happen for my other work (i.e. a piaware release) or when I have enough spare time to do it. Pushing for an early release is going to get you nowhere.

I note that mlat-client and mlat-server _are not tested_, you use them at your own risk and I would expect that individual server operators would have particular client version requirements. Just blindly upgrading to whatever's on master is not a good idea and you shouldn't do it.

If this all makes you unhappy then I suggest you pretend that this repository does not exist and build your own mlat system.

**Pull request closed without merging**
