### PR TITLE
Performance and consistency fixups

### PR DESCRIPTION
**Pull request by toofishes**
Super minor set of changes; just trying to get my feet wet here in this code. Was looking for any obvious optimization opportunities since after dump1090, the FA MLAT client is the next largest CPU user on my Pi.

I'm giving these changes a 24 hour baking period locally at the moment to see what kind of difference they make.

Thoughts?

### CODE REVIEW

**Comment by mutability** [comment]
monotonic_time change seems fine though I don't think it will make a huge difference.

The writable change is not on the critical path and it's probably slower anyway, based on the bytecode; I'd need to see a profile showing it actually matters.

```
>>> dis.dis(flightaware.client.adeptclient.AdeptWriter.writable)
292           0 LOAD_GLOBAL              0 (bool)
              3 LOAD_FAST                0 (self)
              6 LOAD_ATTR                1 (writebuf)
              9 CALL_FUNCTION            1 (1 positional, 0 keyword pair)
             12 RETURN_VALUE
>>> def testit(self):
...   return len(self.writebuf) > 0
... 
>>> dis.dis(testit)
  2           0 LOAD_GLOBAL              0 (len)
              3 LOAD_FAST                0 (self)
              6 LOAD_ATTR                1 (writebuf)
              9 CALL_FUNCTION            1 (1 positional, 0 keyword pair)
             12 LOAD_CONST               1 (0)
             15 COMPARE_OP               4 (>)
             18 RETURN_VALUE
```

If you can squeeze some more out of it that's great! But I suspect it'll be hard work, most of the more obvious lowhanging fruit has been moved into the extension module so the python side is only processing the messages it really needs to (in theory)

**Comment by mutability** [comment]
Oh, I missed the profile numbers in the commit message for the bool/len thing. Interesting!

**Comment by mutability** [comment]
The longer term thing here is probably to move to asyncio now that current raspbian has support for it, asyncore is really creaky.

**Comment by toofishes** [comment]
Here is a snippet of raw profile data.

These definitely aren't big changes, I'll concur with you on that. But you'll see both `time.monotonic` and `writeable` show up in the top 25. Note that monotonic is called 6992063/2621369 = 2.66 times per call to poll; this change will reduce that by nearly one call per loop. And on the writable front, it is in the hot path, as it is called once per loop, looking at the ncalls column.

Agreed on your overall read here- asyncore and friends show up heavily at the top of the profile. My next tweak was going to be to pass `use_poll=True` to the `asyncore.loop()` call to see if that helps. https://docs.python.org/2/library/asyncore.html#asyncore.loop

```
In [1]: import pstats
In [2]: p = pstats.Stats('mlat-client-longer.profile')
In [15]: p.sort_stats('time').print_stats(25)
Thu Jul  7 01:34:50 2016    mlat-client-longer.profile

         107079311 function calls (107079068 primitive calls) in 6455.291 seconds

   Ordered by: internal time
   List reduced from 569 to 25 due to restriction <25>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  2621369 4957.422    0.002 4957.422    0.002 {built-in method select.select}
  2621369  313.939    0.000 6402.788    0.002 asyncore.py:125(poll)
  2529664  159.643    0.000  159.643    0.000 {method 'recv' of '_socket.socket' objects}
  2353867  158.806    0.000  188.429    0.000 adeptclient.py:82(send_mlat)
  2529664  148.803    0.000  786.470    0.000 receiver.py:142(handle_read)
  2529664   75.457    0.000   75.457    0.000 {method 'feed' of '_modes.Reader' objects}
  1526146   49.643    0.000  179.767    0.000 coordinator.py:314(received_df_misc)
  1781919   46.324    0.000  364.095    0.000 coordinator.py:284(input_received_messages)
  2610071   33.217    0.000 1016.835    0.000 asyncore.py:413(handle_read_event)
   524274   29.530    0.000 6432.318    0.012 asyncore.py:192(loop)
   419524   27.663    0.000   30.078    0.000 synthetic_es.py:206(make_position_frame)
   867379   26.477    0.000   96.820    0.000 coordinator.py:332(received_df11)
  6992063   26.216    0.000   26.216    0.000 {built-in method time.monotonic}
  8935582   24.041    0.000   24.041    0.000 {method 'get' of 'dict' objects}
  2610071   21.448    0.000  184.996    0.000 asyncore.py:372(recv)
  2494195   21.104    0.000   21.104    0.000 {method 'pack_into' of 'Struct' objects}
  2610071   20.358    0.000 1037.193    0.000 asyncore.py:81(read)
 15781754   18.461    0.000   18.461    0.000 {method 'append' of 'list' objects}
   419524   18.095    0.000   31.753    0.000 synthetic_es.py:119(cpr_encode)
   629286   17.871    0.000   24.566    0.000 output.py:324(send_frame)
  2621369   17.773    0.000   17.773    0.000 adeptclient.py:291(writable)
   209762   17.708    0.000   27.189    0.000 synthetic_es.py:248(make_velocity_frame)
   210715   17.220    0.000  178.794    0.001 adeptclient.py:228(process_line)
   399486   15.216    0.000   28.584    0.000 coordinator.py:356(received_df17)
   209778   13.687    0.000  154.047    0.001 adeptclient.py:250(process_result_message)
```

**Comment by mutability** [comment]
writable is an odd one: it's not really in the hot path in the sense that it's somewhat independent of the message rate. As the rate picks up and/or the poll loop takes longer to run, what tends to happen is that you process larger batches of messages per loop. Still, no reason not to improve that.

**Pull request merged**
